"""Constant variables for TSA challenge."""

# preprocessing constants
TRAIN_TEST_SPLIT_RATIO = 0.1
IMAGE_DIM = 128
CROP_LOG_INTERVAL = 20

# training constants
BATCH_SIZE = 16
LOG_INTERVAL = 50
VALIDATION_INTERVAL = 200
LR = 2e-1
MOMENTUM = .9
DAMPENING = .5
L2_PENALTY = 5e-7
CLASS_WEIGHTS = (1, 3)
PREDICTION_NORM = CLASS_WEIGHTS[1] / (sum(CLASS_WEIGHTS) - CLASS_WEIGHTS[1])
N_EPOCHS = 10
