"""Constant variables for TSA challenge."""

# preprocessing constants
BATCH_SIZE = 16
TRAIN_TEST_SPLIT_RATIO = 0.1
IMAGE_DIM = 128
LEARNING_RATE = 1e-3
N_TRAIN_STEPS = 1
CROP_LOG_INTERVAL = 20

# training constants
BATCH_SIZE = 24
LOG_INTERVAL = 50
VALIDATION_INTERVAL = 200
LR = 1e-2
MOMENTUM = .9
DAMPENING = .1
L2_PENALTY = 5e-4
CLASS_WEIGHTS = (1, 2)
N_EPOCHS = 9
