"""Constant variables for TSA challenge."""

# preprocessing constants
TRAIN_TEST_SPLIT_RATIO = 0.1
IMAGE_DIM = 128
CROP_LOG_INTERVAL = 20

# training constants
BATCH_SIZE = 40
LOG_INTERVAL = 5
VALIDATION_INTERVAL = 200
LR = 1e-4
MOMENTUM = .9
DAMPENING = .5
L2_PENALTY = 10e-4
CLASS_WEIGHTS = (1, 3)
PREDICTION_NORM = CLASS_WEIGHTS[1] / (sum(CLASS_WEIGHTS) - CLASS_WEIGHTS[1])
N_EPOCHS = 15
